M48
; DRILL file {KiCad 8.0.5} date 2024-10-19T23:11:01+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-19T23:11:01+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X208.295Y-76.061
X208.295Y-80.911
T2
X211.325Y-75.761
X211.325Y-81.211
M30
